travis:
  secure:
    BINSTAR_TOKEN: lUVs27mLmQkTvfmyuJr8eG6wOWQDt8KfrcaUyqgu6QeC0veAfRy1HFvMmyNqYcJMBXdsZ0agFDcyBxVeG8edQYbiOW+RfwkM0LX8U/ZWw4YVtJ4ZVpz3bREk5LqbKKQwVoiVWFSPCyJvvWFIP8vxdO3Ph+8WgtTMY4m+rEg2cFAw980b3geVo36R+g8gfg63sK9qgcGKTFTpuhoyISpbERjv8IqEgTZntwZngxla1RpjpyQMjY2ELMrADphRUyYwabc2v5hawdRPGJPQXub8icDmibRR/mbraD0MMHWbGbio2dINfljNdO4oM2kDdbfo6IXpjRT54KFWcZa5/y1fo/ZeuMMM9EFlkxHOuAZfZzbVX+4F+s+QtI8C4SlWuotcytwjJXtj/NLyZThzF1/8kD+2KmrCGkKAMuAlBX/OSuhdtBOzm+1SiPV3Z0xiE3coVM4AVPV6AcYWGl/iinKn/snScJhe17xpiMK5OZQ5HSeaRGTXz2XqhW9exmSGQEZKG1xeoCZ9PTTVni6kV2RQz+6hlhhVySwSuM1tiuYpuUjPaXq+gCodAJL22ntJme3tRLMBFo1ERI2JoA8WTb16LpWDvQGSBlIbz3C5Pr809tMBjlIR9EHws3fmCzMk7WJV4gl8cjLYU+TW/itVdcZCj0vOmVJVWGDlqB78omsAHR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
